# Generated by Django 3.2.5 on 2021-08-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parametry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jednostka', models.TextField(choices=[('1', 'g liq.'), ('2', 'j.m.'), ('3', 'op'), ('4', 'krople'), ('5', 'ml'), ('5', 'g')])),
                ('producent', models.TextField(choices=[('1', 'Medana 50000j.m./ml'), ('2', 'Hasco 4500j.m./ml')])),
                ('ilosc', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ilegramliq', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ilejm', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ilegram', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ilekropli', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ileml', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('ileop', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('skladnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitamin.skladnik')),
            ],
        ),
    ]
