# Generated by Django 3.2.5 on 2021-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0003_auto_20211120_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboczareceptura',
            name='producent',
            field=models.TextField(choices=[('1', 'producent 1'), ('2', 'producent 2')], default=None),
        ),
    ]
