# Generated by Django 3.2.5 on 2021-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0006_alter_roboczareceptura_producent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboczareceptura',
            name='producent',
            field=models.TextField(blank=True, choices=[('1', 'Hasco 4500j.m./ml'), ('2', 'Medana 50000j.m./ml'), ('3', 'Hasco 0,3g/ml')], null=True),
        ),
    ]
