# Generated by Django 3.2.5 on 2021-11-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0007_alter_roboczareceptura_producent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='ale',
            new_name='czesci',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='dziadejos',
            new_name='gramy',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='janko',
            new_name='jednostki',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='okejos',
            new_name='krople',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='sianko',
            new_name='mililitry',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='super',
            new_name='opakowania',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='wale',
            new_name='sztuki',
        ),
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='wodziejos',
            new_name='tabletki',
        ),
    ]
