# Generated by Django 3.2.5 on 2021-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0008_auto_20211128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboczareceptura',
            name='jednostka_z_rec',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
