# Generated by Django 3.2.5 on 2021-11-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0009_roboczareceptura_jednostka_z_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roboczareceptura',
            old_name='jednostka_z_rec',
            new_name='jednostka_z_recepty',
        ),
    ]
