# Generated by Django 3.2.5 on 2021-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0010_rename_jednostka_z_rec_roboczareceptura_jednostka_z_recepty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboczareceptura',
            name='ilosc_na_recepcie',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
